# Generated by Django 4.0.6 on 2022-08-01 16:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestbedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='testbeds/')),
            ],
        ),
    ]
